version: "3"

services:
  next:
    # Use a custom image for nuxt
    build:
      context: ../
      dockerfile: docker/Dockerfile
    container_name: fassets-fe
    restart: always
    ports:
      - "80:3000"
    volumes:
      - ./../src/:/app
      - /app/node_modules/
